# Nixpacks configuration for Railway deployment
[phases.build]
cmds = [
    'python manage.py collectstatic --noinput',
    'chmod +x start.sh'
]

[start]
cmd = './start.sh'

[variables]
PYTHONPATH = '/app'