# Generated by Django 4.2.24 on 2025-09-12 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tools", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="tool",
            index=models.Index(
                fields=["is_published", "-created_at"],
                name="tools_tool_is_publ_7ddf58_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="tool",
            index=models.Index(
                fields=["is_published", "-view_count"],
                name="tools_tool_is_publ_e8b6a8_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="tool",
            index=models.Index(
                fields=["is_published", "-rating_sum"],
                name="tools_tool_is_publ_60dad5_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="tool",
            index=models.Index(
                fields=["rating_sum"], name="tools_tool_rating__e97a41_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tool",
            index=models.Index(
                fields=["rating_count"], name="tools_tool_rating__e476c9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tool",
            index=models.Index(fields=["status"], name="tools_tool_status_de6bf1_idx"),
        ),
        migrations.AddIndex(
            model_name="tool",
            index=models.Index(
                fields=["pricing_model"], name="tools_tool_pricing_616fe2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tool",
            index=models.Index(fields=["slug"], name="tools_tool_slug_f69786_idx"),
        ),
        migrations.AddIndex(
            model_name="tool",
            index=models.Index(
                fields=["category", "pricing_model"],
                name="tools_tool_categor_80ef6a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="tool",
            index=models.Index(
                fields=["category", "status"], name="tools_tool_categor_919f08_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tool",
            index=models.Index(
                fields=["github_stars"], name="tools_tool_github__83c9ed_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tool",
            index=models.Index(
                fields=["-created_at"], name="tools_tool_created_1fd619_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tool",
            index=models.Index(
                fields=["-updated_at"], name="tools_tool_updated_9ad3ae_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tool",
            index=models.Index(
                fields=["-ai_last_updated"], name="tools_tool_ai_last_723ed6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tool",
            index=models.Index(
                fields=["category", "is_published", "-view_count"],
                name="tools_tool_categor_355cfb_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="tool",
            index=models.Index(
                fields=["is_featured", "is_published", "-created_at"],
                name="tools_tool_is_feat_7fc976_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="tool",
            index=models.Index(
                fields=["is_trending", "is_published", "-rating_sum"],
                name="tools_tool_is_tren_f7771d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="toolcomparison",
            index=models.Index(
                fields=["is_published", "-created_at"],
                name="tools_toolc_is_publ_2be455_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="toolcomparison",
            index=models.Index(
                fields=["is_published", "-view_count"],
                name="tools_toolc_is_publ_1d0130_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="toolcomparison",
            index=models.Index(fields=["slug"], name="tools_toolc_slug_0513a0_idx"),
        ),
        migrations.AddIndex(
            model_name="toolcomparison",
            index=models.Index(
                fields=["author"], name="tools_toolc_author__3e23d3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="toolcomparison",
            index=models.Index(
                fields=["ai_generated"], name="tools_toolc_ai_gene_4025d7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="toolcomparison",
            index=models.Index(
                fields=["-created_at"], name="tools_toolc_created_b01929_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="toolcomparison",
            index=models.Index(
                fields=["-updated_at"], name="tools_toolc_updated_dabe5d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="toolreview",
            index=models.Index(
                fields=["tool", "-created_at"], name="tools_toolr_tool_id_21bb3e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="toolreview",
            index=models.Index(
                fields=["user", "-created_at"], name="tools_toolr_user_id_d20c8b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="toolreview",
            index=models.Index(
                fields=["tool", "rating"], name="tools_toolr_tool_id_07f5a0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="toolreview",
            index=models.Index(
                fields=["tool", "is_verified"], name="tools_toolr_tool_id_788eb1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="toolreview",
            index=models.Index(
                fields=["tool", "is_featured"], name="tools_toolr_tool_id_fe8e15_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="toolreview",
            index=models.Index(fields=["rating"], name="tools_toolr_rating_d5f88d_idx"),
        ),
        migrations.AddIndex(
            model_name="toolreview",
            index=models.Index(
                fields=["is_verified"], name="tools_toolr_is_veri_ca8397_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="toolreview",
            index=models.Index(
                fields=["is_featured"], name="tools_toolr_is_feat_19ed20_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="toolreview",
            index=models.Index(
                fields=["helpful_count"], name="tools_toolr_helpful_200900_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="toolreview",
            index=models.Index(
                fields=["-created_at"], name="tools_toolr_created_ad3a9e_idx"
            ),
        ),
    ]
