# Generated by Django 4.2.24 on 2025-09-21 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tools", "0003_toolcomparison_feature_matrix_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name='toolcomparison',
            name='sections',
            field=models.JSONField(default=dict, help_text='Structured comparison sections with detailed analysis'),
        ),
        migrations.AddField(
            model_name='toolcomparison',
            name='feature_matrix',
            field=models.JSONField(default=dict, help_text='Feature comparison matrix with detailed scoring'),
        ),
        migrations.AddField(
            model_name='toolcomparison',
            name='tool_analysis',
            field=models.JSONField(default=dict, help_text='Detailed analysis for each tool including pros/cons'),
        ),
        migrations.AddField(
            model_name='toolcomparison',
            name='use_case_recommendations',
            field=models.JSONField(default=dict, help_text='Specific use cases and recommendations for each tool'),
        ),
        migrations.AddField(
            model_name='toolcomparison',
            name='summary_table',
            field=models.JSONField(default=dict, help_text='Summary comparison table data'),
        ),
    ]
