# Generated by Django 4.2.24 on 2025-10-02 18:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tools", "0004_auto_20250921_0251"),
    ]

    operations = [
        migrations.CreateModel(
            name="ComparisonRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "session_id",
                    models.CharField(
                        db_index=True,
                        help_text="Anonymous session ID for non-logged-in users",
                        max_length=100,
                    ),
                ),
                (
                    "user_query",
                    models.TextField(
                        help_text="User's specific comparison question or requirements"
                    ),
                ),
                (
                    "comparison_context",
                    models.JSONField(
                        default=dict,
                        help_text="Additional context: use case, team size, budget, etc.",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "ai_model_used",
                    models.CharField(
                        default="openai/gpt-4o-mini",
                        help_text="AI model used for generation",
                        max_length=100,
                    ),
                ),
                (
                    "processing_time",
                    models.FloatField(
                        blank=True,
                        help_text="Time taken to generate comparison (seconds)",
                        null=True,
                    ),
                ),
                (
                    "comparison_result",
                    models.JSONField(
                        default=dict,
                        help_text="Structured AI-generated comparison data",
                    ),
                ),
                (
                    "raw_response",
                    models.TextField(
                        blank=True, help_text="Raw AI response for debugging"
                    ),
                ),
                ("tokens_used", models.IntegerField(default=0)),
                (
                    "cost_estimate",
                    models.DecimalField(decimal_places=6, default=0.0, max_digits=10),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                (
                    "was_helpful",
                    models.BooleanField(
                        blank=True,
                        help_text="User feedback on comparison quality",
                        null=True,
                    ),
                ),
                ("feedback_comment", models.TextField(blank=True)),
                (
                    "tool1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comparisons_as_tool1",
                        to="tools.tool",
                    ),
                ),
                (
                    "tool2",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comparisons_as_tool2",
                        to="tools.tool",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comparison_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "AI Comparison Request",
                "verbose_name_plural": "AI Comparison Requests",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["tool1", "tool2", "-created_at"],
                        name="tools_compa_tool1_i_cf273d_idx",
                    ),
                    models.Index(
                        fields=["status", "-created_at"],
                        name="tools_compa_status_7bff4f_idx",
                    ),
                    models.Index(
                        fields=["session_id", "-created_at"],
                        name="tools_compa_session_5e2c04_idx",
                    ),
                    models.Index(
                        fields=["user", "-created_at"],
                        name="tools_compa_user_id_e69b57_idx",
                    ),
                ],
            },
        ),
    ]
