# Generated by Django 4.2.24 on 2025-09-06 16:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NewsletterSubscriber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "source",
                    models.CharField(
                        default="website",
                        help_text="Where the subscriber came from",
                        max_length=50,
                    ),
                ),
                (
                    "preferences",
                    models.JSONField(
                        default=dict, help_text="Subscriber preferences and tags"
                    ),
                ),
            ],
            options={
                "verbose_name": "Newsletter Subscriber",
                "verbose_name_plural": "Newsletter Subscribers",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SiteConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "site_name",
                    models.CharField(default="CloudEngineered", max_length=100),
                ),
                (
                    "site_description",
                    models.TextField(
                        default="Comprehensive reviews and comparisons of cloud engineering and DevOps tools"
                    ),
                ),
                (
                    "site_logo",
                    models.ImageField(blank=True, null=True, upload_to="site/"),
                ),
                (
                    "site_favicon",
                    models.ImageField(blank=True, null=True, upload_to="site/"),
                ),
                (
                    "contact_email",
                    models.EmailField(
                        default="contact@cloudengineered.io", max_length=254
                    ),
                ),
                (
                    "support_email",
                    models.EmailField(
                        default="support@cloudengineered.io", max_length=254
                    ),
                ),
                ("twitter_url", models.URLField(blank=True)),
                ("linkedin_url", models.URLField(blank=True)),
                ("github_url", models.URLField(blank=True)),
                ("google_analytics_id", models.CharField(blank=True, max_length=50)),
                ("google_search_console_code", models.TextField(blank=True)),
                (
                    "default_meta_description",
                    models.TextField(
                        default="Discover and compare the best cloud engineering and DevOps tools. In-depth reviews, comparisons, and insights for technical professionals.",
                        max_length=160,
                    ),
                ),
                ("enable_user_registration", models.BooleanField(default=True)),
                ("enable_comments", models.BooleanField(default=True)),
                ("enable_newsletter", models.BooleanField(default=True)),
                ("maintenance_mode", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Site Configuration",
                "verbose_name_plural": "Site Configuration",
            },
        ),
    ]
