# Generated by Django 4.2.24 on 2025-09-10 19:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SearchAnalytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True)),
                ("total_searches", models.PositiveIntegerField(default=0)),
                ("unique_queries", models.PositiveIntegerField(default=0)),
                ("unique_users", models.PositiveIntegerField(default=0)),
                ("avg_results_per_search", models.FloatField(default=0)),
                ("zero_result_searches", models.PositiveIntegerField(default=0)),
                ("avg_response_time", models.FloatField(default=0)),
                ("top_queries", models.JSONField(default=list)),
                ("filter_usage", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "search_analytics",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="SearchSuggestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "suggestion",
                    models.CharField(db_index=True, max_length=255, unique=True),
                ),
                ("category", models.CharField(blank=True, max_length=100)),
                ("priority", models.PositiveIntegerField(default=1)),
                ("search_count", models.PositiveIntegerField(default=0)),
                ("last_searched", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "search_suggestions",
                "ordering": ["-priority", "-search_count", "suggestion"],
                "indexes": [
                    models.Index(
                        fields=["suggestion"], name="search_sugg_suggest_0a63f1_idx"
                    ),
                    models.Index(
                        fields=["-priority", "-search_count"],
                        name="search_sugg_priorit_1cbebf_idx",
                    ),
                    models.Index(
                        fields=["is_active", "-priority"],
                        name="search_sugg_is_acti_8faf09_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="PopularSearch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("query", models.CharField(db_index=True, max_length=255, unique=True)),
                ("search_count", models.PositiveIntegerField(default=1)),
                ("unique_users", models.PositiveIntegerField(default=1)),
                ("last_week_count", models.PositiveIntegerField(default=0)),
                ("last_month_count", models.PositiveIntegerField(default=0)),
                ("first_searched", models.DateTimeField(auto_now_add=True)),
                ("last_searched", models.DateTimeField(auto_now=True)),
                ("is_trending", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "popular_searches",
                "ordering": ["-search_count", "-last_searched"],
                "indexes": [
                    models.Index(
                        fields=["-search_count"], name="popular_sea_search__b72fa3_idx"
                    ),
                    models.Index(
                        fields=["is_trending", "-search_count"],
                        name="popular_sea_is_tren_ab9035_idx",
                    ),
                    models.Index(
                        fields=["-last_searched"], name="popular_sea_last_se_deb4c6_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SearchQuery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("query", models.CharField(db_index=True, max_length=255)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("content_type", models.CharField(blank=True, max_length=50)),
                ("category", models.CharField(blank=True, max_length=100)),
                ("sort_by", models.CharField(blank=True, max_length=50)),
                ("results_count", models.PositiveIntegerField(default=0)),
                ("clicked_result", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("response_time", models.FloatField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="search_queries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "search_queries",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["query", "-created_at"],
                        name="search_quer_query_1bea7d_idx",
                    ),
                    models.Index(
                        fields=["user", "-created_at"],
                        name="search_quer_user_id_486cee_idx",
                    ),
                    models.Index(
                        fields=["-created_at"], name="search_quer_created_824a49_idx"
                    ),
                ],
            },
        ),
    ]
