# Generated by Django 4.2.24 on 2025-10-02 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_search_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="newslettersubscriber",
            name="emails_opened",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="newslettersubscriber",
            name="emails_sent",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="newslettersubscriber",
            name="ip_address",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="newslettersubscriber",
            name="is_verified",
            field=models.BooleanField(default=False, help_text="Email verified"),
        ),
        migrations.AddField(
            model_name="newslettersubscriber",
            name="last_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="newslettersubscriber",
            name="links_clicked",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="newslettersubscriber",
            name="name",
            field=models.CharField(
                blank=True, help_text="Subscriber's name (optional)", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="newslettersubscriber",
            name="unsubscribed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="newslettersubscriber",
            name="user_agent",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="newslettersubscriber",
            name="verification_token",
            field=models.CharField(
                db_index=True, default="", max_length=64, unique=True
            ),
        ),
        migrations.AddField(
            model_name="newslettersubscriber",
            name="verified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="newslettersubscriber",
            name="email",
            field=models.EmailField(db_index=True, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name="newslettersubscriber",
            name="is_active",
            field=models.BooleanField(default=True, help_text="Active subscription"),
        ),
        migrations.AlterField(
            model_name="newslettersubscriber",
            name="preferences",
            field=models.JSONField(
                default=dict,
                help_text="Subscriber preferences: {'frequency': 'weekly', 'categories': ['devops', 'cloud']}",
            ),
        ),
        migrations.AddIndex(
            model_name="newslettersubscriber",
            index=models.Index(
                fields=["email", "is_verified", "is_active"],
                name="core_newsle_email_2e8b8b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="newslettersubscriber",
            index=models.Index(
                fields=["verification_token"], name="core_newsle_verific_d12d04_idx"
            ),
        ),
    ]
