# Generated by Django 4.2.24 on 2025-09-10 19:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AIModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("display_name", models.CharField(max_length=200)),
                ("max_tokens", models.IntegerField(default=4096)),
                ("supports_functions", models.BooleanField(default=False)),
                ("supports_vision", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "cost_per_1k_input_tokens",
                    models.DecimalField(
                        decimal_places=6, default=0.0015, max_digits=10
                    ),
                ),
                (
                    "cost_per_1k_output_tokens",
                    models.DecimalField(decimal_places=6, default=0.002, max_digits=10),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["provider", "name"],
            },
        ),
        migrations.CreateModel(
            name="AIProvider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "api_key_name",
                    models.CharField(
                        help_text="Environment variable name for API key",
                        max_length=100,
                    ),
                ),
                ("base_url", models.URLField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("rate_limit_per_minute", models.IntegerField(default=60)),
                (
                    "cost_per_1k_tokens",
                    models.DecimalField(decimal_places=6, default=0.002, max_digits=10),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ContentGeneration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "input_data",
                    models.JSONField(
                        help_text="Input parameters for content generation"
                    ),
                ),
                (
                    "generated_prompt",
                    models.TextField(blank=True, help_text="Final prompt sent to AI"),
                ),
                ("generated_content", models.TextField(blank=True)),
                (
                    "raw_response",
                    models.JSONField(
                        blank=True, help_text="Raw AI response", null=True
                    ),
                ),
                ("tokens_used", models.IntegerField(default=0)),
                (
                    "estimated_cost",
                    models.DecimalField(decimal_places=6, default=0.0, max_digits=10),
                ),
                (
                    "processing_time",
                    models.FloatField(
                        default=0.0, help_text="Processing time in seconds"
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                ("object_id", models.PositiveIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "initiated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_generations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ContentTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "template_type",
                    models.CharField(
                        choices=[
                            ("tool_review", "Tool Review"),
                            ("comparison", "Tool Comparison"),
                            ("guide", "How-to Guide"),
                            ("news", "News Article"),
                            ("tutorial", "Tutorial"),
                            ("overview", "Tool Overview"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "system_prompt",
                    models.TextField(help_text="System prompt for AI model"),
                ),
                (
                    "user_prompt_template",
                    models.TextField(
                        help_text="User prompt template with placeholders"
                    ),
                ),
                (
                    "output_format",
                    models.TextField(help_text="Expected output format/structure"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="templates",
                        to="ai.aimodel",
                    ),
                ),
            ],
            options={
                "ordering": ["template_type", "name"],
            },
        ),
        migrations.CreateModel(
            name="ContentQuality",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("readability_score", models.FloatField(blank=True, null=True)),
                ("word_count", models.IntegerField(default=0)),
                ("paragraph_count", models.IntegerField(default=0)),
                ("has_headings", models.BooleanField(default=False)),
                ("has_links", models.BooleanField(default=False)),
                ("has_lists", models.BooleanField(default=False)),
                (
                    "technical_accuracy",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (1, "Poor"),
                            (2, "Below Average"),
                            (3, "Average"),
                            (4, "Good"),
                            (5, "Excellent"),
                        ],
                        null=True,
                    ),
                ),
                (
                    "clarity",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (1, "Poor"),
                            (2, "Below Average"),
                            (3, "Average"),
                            (4, "Good"),
                            (5, "Excellent"),
                        ],
                        null=True,
                    ),
                ),
                (
                    "completeness",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (1, "Poor"),
                            (2, "Below Average"),
                            (3, "Average"),
                            (4, "Good"),
                            (5, "Excellent"),
                        ],
                        null=True,
                    ),
                ),
                (
                    "seo_optimization",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (1, "Poor"),
                            (2, "Below Average"),
                            (3, "Average"),
                            (4, "Good"),
                            (5, "Excellent"),
                        ],
                        null=True,
                    ),
                ),
                ("overall_score", models.FloatField(blank=True, null=True)),
                ("requires_human_review", models.BooleanField(default=False)),
                ("review_notes", models.TextField(blank=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("approved_for_publishing", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "generation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quality",
                        to="ai.contentgeneration",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_content",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="contentgeneration",
            name="template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="generations",
                to="ai.contenttemplate",
            ),
        ),
        migrations.AddField(
            model_name="aimodel",
            name="provider",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="models",
                to="ai.aiprovider",
            ),
        ),
        migrations.CreateModel(
            name="AIUsageStatistics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("total_requests", models.IntegerField(default=0)),
                ("total_tokens", models.IntegerField(default=0)),
                ("total_input_tokens", models.IntegerField(default=0)),
                ("total_output_tokens", models.IntegerField(default=0)),
                (
                    "total_cost",
                    models.DecimalField(decimal_places=4, default=0.0, max_digits=10),
                ),
                ("average_response_time", models.FloatField(default=0.0)),
                ("success_rate", models.FloatField(default=0.0)),
                ("error_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usage_stats",
                        to="ai.aimodel",
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usage_stats",
                        to="ai.aiprovider",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
                "unique_together": {("provider", "model", "date")},
            },
        ),
        migrations.AlterUniqueTogether(
            name="aimodel",
            unique_together={("provider", "name")},
        ),
    ]
