# Generated by Django 4.2.24 on 2025-09-12 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="analyticsevent",
            index=models.Index(
                fields=["timestamp"], name="analytics_a_timesta_aef2a5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="analyticsevent",
            index=models.Index(
                fields=["event_type"], name="analytics_a_event_t_a460ec_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="analyticsevent",
            index=models.Index(fields=["user"], name="analytics_a_user_id_3326ea_idx"),
        ),
        migrations.AddIndex(
            model_name="analyticsevent",
            index=models.Index(
                fields=["session_id"], name="analytics_a_session_8757e5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="analyticsevent",
            index=models.Index(
                fields=["event_type", "user", "timestamp"],
                name="analytics_a_event_t_579e0e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="analyticsevent",
            index=models.Index(
                fields=["content_type", "object_id", "timestamp"],
                name="analytics_a_content_ac669b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="analyticsevent",
            index=models.Index(
                fields=["user", "event_type"], name="analytics_a_user_id_7df679_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="analyticsevent",
            index=models.Index(
                fields=["-timestamp"], name="analytics_a_timesta_b8f215_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="analyticsevent",
            index=models.Index(
                fields=["event_type", "-timestamp"],
                name="analytics_a_event_t_c6fe80_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="pageview",
            index=models.Index(
                fields=["page_url"], name="analytics_p_page_ur_ae0ca5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pageview",
            index=models.Index(
                fields=["page_type"], name="analytics_p_page_ty_5af892_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pageview",
            index=models.Index(
                fields=["device_type"], name="analytics_p_device__a59989_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pageview",
            index=models.Index(
                fields=["browser"], name="analytics_p_browser_3463a2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pageview",
            index=models.Index(
                fields=["country"], name="analytics_p_country_59a416_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pageview",
            index=models.Index(
                fields=["utm_source", "created_at"],
                name="analytics_p_utm_sou_129f54_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="pageview",
            index=models.Index(
                fields=["utm_medium", "created_at"],
                name="analytics_p_utm_med_7ae2f4_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="pageview",
            index=models.Index(
                fields=["utm_campaign", "created_at"],
                name="analytics_p_utm_cam_7cf6b7_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="pageview",
            index=models.Index(
                fields=["page_type", "country", "created_at"],
                name="analytics_p_page_ty_3b98fc_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="pageview",
            index=models.Index(
                fields=["device_type", "browser", "created_at"],
                name="analytics_p_device__8ba44b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="pageview",
            index=models.Index(
                fields=["user", "page_type"], name="analytics_p_user_id_974d17_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pageview",
            index=models.Index(
                fields=["-created_at"], name="analytics_p_created_44ec6b_idx"
            ),
        ),
    ]
